int getInt(char mensaje[]);
float getFloat(char mensaje[]);
char getChar(char mensaje[]);
void stringToUpper(char caracter[]);
int esNumerico(char str[]);
int esTelefono(char str[]);
int esSoloLetras (char str[]);
int esAlfaNumerico(char str[]);
void getString(char mensaje[], char input[]);
int getStringLetras(char mensaje[], char input[]);
int getStringNumeros(char mensaje[], char input[]);
 int getAlfaNumerico(char mensaje[], char input[]);
